// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Sample1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sample1() {
    // Test name: sample-1
    // Step # | name | target | value | comment
    // 1 | open | https://www.amazon.in/ |  | 
    driver.get("https://www.amazon.in/");
    // 2 | setWindowSize | 550x680 |  | 
    driver.manage().window().setSize(new Dimension(550, 680));
    // 3 | click | id=twotabsearchtextbox |  | 
    driver.findElement(By.id("twotabsearchtextbox")).click();
    // 4 | type | id=twotabsearchtextbox | dell | 
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys("dell");
    // 5 | sendKeys | id=twotabsearchtextbox | ${KEY_ENTER} | 
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Keys.ENTER);
    // 6 | mouseOver | css=.nav-logo-link |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".nav-logo-link"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
